### ISSUE TITLE
tutorial-contents/403_RNN_regressor.py  bug report

### ISSUE THREAD

**Issue by njuHan** [MorvanZhou/PyTorch-Tutorial#46]
你好， 
文件tutorial-contents/403_RNN_regressor.py 中的这段代码
```
r_out = r_out.view(-1, 32)
outs = self.out(r_out)
return outs, h_state
```
outs的shape是 10x1,  与(batch, time_step, input_size) 不匹配， 导致RuntimeError: input and target shapes do not match: input [10 x 1], target [1 x 10 x 1] 
是否可以这样直接添加一个维度，匹配(batch, time_step, input_size)
```
r_out = r_out.view(-1, 32)  
outs = self.out(r_out) 
return torch.unsqueeze(outs,0), h_state
```

**Comment by MorvanZhou** [comment]
请问你是用的pytorch什么版本， 我这边测的0.4这个版本没有错误。可能是版本问题

**Comment by keineahnung2345** [comment]
@MorvanZhou I use 0.4.1 and get the same error as @njuHan .

> Traceback (most recent call last):
  File "<stdin>", line 12, in <module>
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/loss.py", line 421, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py", line 1716, in mse_loss
    return _pointwise_loss(lambda a, b: (a - b) ** 2, torch._C._nn.mse_loss, input, target, reduction)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py", line 1674, in _pointwise_loss
    return lambd_optimized(input, target, reduction)
RuntimeError: input and target shapes do not match: input [10 x 1], target [1 x 10 x 1] at /pytorch/aten/src/THNN/generic/MSECriterion.c:12
